#!/usr/bin/env python3
""""
TPE Calculator v0.1 — Integrated Radiation Damage Calculation Toolkit

Menu-driven interface for:
  1. TDE Calculation (Ed_calc, LAMMPS MD knock-on atom simulation)
  2. Plot Ed Convergence (Ed_plot, matplotlib visualization)
  3. DPA Calculator (NRT / ARC-DPA / CB-DPA analytical models)
  4. Clean Up (remove intermediate and result files)
  9. Environment (set mpirun & LAMMPS paths)
  0. Exit

Usage:
  python3 main.py
"""

import os
import sys
import subprocess
import shutil
import glob
import re

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ED_CALC_DIR = os.path.join(BASE_DIR, "Ed_calc")
ED_PLOT_DIR = os.path.join(BASE_DIR, "Ed_plot")
DPA_CALC_DIR = os.path.join(BASE_DIR, "DPA_calc")
POT_FILES_DIR = os.path.join(BASE_DIR, "pot_files")
DATA_FILES_DIR = os.path.join(BASE_DIR, "custom_data_files")

# ── Periodic table: element symbol → atomic mass (g/mol) ────────────────────
PERIODIC_TABLE = {
    "Li": 6.941, "Be": 9.012, "B": 10.811, "C": 12.011, "N": 14.007,
    "O": 15.999, "F": 18.998, "Na": 22.990, "Mg": 24.305, "Al": 26.982,
    "Si": 28.086, "P": 30.974, "S": 32.065, "K": 39.098, "Ca": 40.078,
    "Sc": 44.956, "Ti": 47.867, "V": 50.942, "Cr": 51.996, "Mn": 54.938,
    "Fe": 55.845, "Co": 58.933, "Ni": 58.693, "Cu": 63.546, "Zn": 65.38,
    "Y": 88.906, "Zr": 91.224, "Nb": 92.906, "Mo": 95.95, "Ru": 101.07,
    "Rh": 102.906, "Pd": 106.42, "Ag": 107.868, "Cd": 112.411,
    "Hf": 178.49, "Ta": 180.948, "W": 183.84, "Re": 186.207,
    "Os": 190.23, "Ir": 192.217, "Pt": 195.084, "Au": 196.967,
    "Pb": 207.2, "Bi": 208.980, "U": 238.029,
}


# ═══════════════════════════════════════════════════════════════════════════
#  Menu
# ═══════════════════════════════════════════════════════════════════════════

def show_menu():
    print()
    print("=" * 60)
    print("  TPE Calculator v0.2.1")
    print("  Radiation Damage Calculation Toolkit")
    print("=" * 60)
    print("  1. TDE Calculation  (Ed_calc, LAMMPS MD)")
    print("  2. Plot Ed         (Ed_plot, convergence)")
    print("  3. DPA Calculator  (NRT / ARC-DPA / CB-DPA)")
    print("  4. Clean Up        (remove all generated files)")
    print("  9. Environment     (set mpirun & LAMMPS paths)")
    print("  0. Exit")
    print("=" * 60)


# ═══════════════════════════════════════════════════════════════════════════
#  Option 1: TDE Calculation
# ═══════════════════════════════════════════════════════════════════════════

def parse_run_ed_params():
    """Read key parameters from Ed_calc/run_Ed.sh."""
    params = {}
    run_ed = os.path.join(ED_CALC_DIR, "run_Ed.sh")
    if not os.path.exists(run_ed):
        return params
    with open(run_ed) as f:
        for line in f:
            m = re.match(r'^(\w+)=(\S+)', line.strip())
            if m and m.group(1) in (
                "CONFIG_SOURCE", "NCORE", "NJOB", "NCONFIG", "NDIR_PER_CONFIG",
                "SIMTIME", "EMIN", "EMAX", "ESTEP", "TEMP",
                "DEFECT_METHOD", "VERBOSE",
            ):
                val = m.group(2).strip('"').strip("'")
                params[m.group(1)] = val
    return params


def update_run_ed_param(name, value):
    """Update a single parameter in Ed_calc/run_Ed.sh using sed-style replacement."""
    run_ed = os.path.join(ED_CALC_DIR, "run_Ed.sh")
    with open(run_ed) as f:
        lines = f.readlines()
    pattern = re.compile(r'^(' + re.escape(name) + r'=)(\S+)')
    updated = False
    for i, line in enumerate(lines):
        m = pattern.match(line)
        if m:
            lines[i] = f"{m.group(1)}{value}\n"
            updated = True
            break
    if updated:
        with open(run_ed, 'w') as f:
            f.writelines(lines)
    return updated


def generate_alloy_conf(name, n_elements, elements, masses, lattice, potential,
                        config_source, crystal_structure="bcc",
                        lco_prefix="../custom_data_files/data"):
    """Write alloy.conf with the user-specified material parameters."""
    conf = os.path.join(ED_CALC_DIR, "alloy.conf")
    with open(conf, 'w') as f:
        f.write("#==============================================================================\n")
        f.write("# alloy.conf — Generated by main.py\n")
        f.write("#==============================================================================\n")
        f.write(f'\nALLOY_NAME="{name}"\n')
        f.write(f'N_ELEMENTS={n_elements}\n')
        f.write(f'LATTICE_CONSTANT={lattice}\n')
        f.write(f'ELEMENT_NAMES="{elements}"\n')
        f.write(f'ELEMENT_MASSES="{masses}"\n')
        f.write(f'\nPOTENTIAL_FILE="{potential}"\n')
        f.write(f'\nCONFIG_SOURCE="{config_source}"\n')
        f.write(f'\nCRYSTAL_STRUCTURE="{crystal_structure}"\n')
        if config_source == "custom":
            f.write(f'\nLCO_DATA_PREFIX="{lco_prefix}"\n')


def run_tde_calc():
    print("\n" + "=" * 60)
    print("  TDE Calculation — Material Setup")
    print("=" * 60)

    # ── Step 1: Elements ────────────────────────────────────────────────────
    print("\nStep 1: Enter element symbols (space-separated).")
    print("  Examples:  Hf Nb Zr Ti Ta   |   W Ta Cr V   |   Ta   |   Ma")
    default_elems = "Hf Nb Zr Ti Ta"
    elem_str = input(f"\n  Elements [{default_elems}]: ").strip()
    if not elem_str:
        elem_str = default_elems
    elems = elem_str.split()
    n_elements = len(elems)

    # Look up masses
    masses = []
    manual_mass = False
    for e in elems:
        if e in PERIODIC_TABLE:
            masses.append(f"{PERIODIC_TABLE[e]:.3f}")
        else:
            print(f"  '{e}' not in periodic table. Enter atomic mass manually.")
            m = input(f"    Mass of {e} (g/mol): ").strip()
            if not m:
                print("  ERROR: mass is required for unknown elements.")
                return
            masses.append(m)
            manual_mass = True
    masses_str = " ".join(masses)

    if manual_mass:
        print(f"  Masses: {masses_str} (some manually entered)")
    else:
        print(f"  Auto-looked up: {masses_str}")

    # ── Step 2: Potential ────────────────────────────────────────────────────
    print(f"\nStep 2: Select potential file from {os.path.relpath(POT_FILES_DIR, BASE_DIR)}/")
    pot_list = sorted(os.listdir(POT_FILES_DIR)) if os.path.exists(POT_FILES_DIR) else []
    if not pot_list:
        print(f"  No files found in {os.path.relpath(POT_FILES_DIR, BASE_DIR)}/.")
        print("  Please place a potential file in this directory first.")
        return
    for i, f in enumerate(pot_list):
        print(f"    {i+1}. {f}")
    try:
        choice = int(input(f"\n  Select [1-{len(pot_list)}]: ").strip())
        if choice < 1 or choice > len(pot_list):
            print("  Invalid selection.")
            return
    except (ValueError, EOFError):
        print("  Invalid input.")
        return
    pot_file = os.path.join("../pot_files", pot_list[choice - 1])
    print(f"  Selected: {pot_file}")

    # ── Step 3: Configuration source + lattice ───────────────────────────────
    print("\nStep 3: Configuration source.")
    print("  auto   = program generates random solid solution (BCC / FCC)")
    print("  custom = user provides data files in custom_data_files/")
    config_source = input("  Source [auto]: ").strip().lower()
    if not config_source:
        config_source = "auto"
    if config_source not in ("auto", "custom"):
        print("  Invalid choice. Must be 'auto' or 'custom'.")
        return

    crystal_structure = "bcc"
    if config_source == "auto":
        print("  Crystal structure (auto mode supports bcc and fcc only.")
        print("  For other structures, use 'custom' config source.)")
        crystal_structure = input("  Structure [bcc]: ").strip().lower()
        if not crystal_structure:
            crystal_structure = "bcc"
        if crystal_structure not in ("bcc", "fcc"):
            print("  Invalid choice. Must be 'bcc' or 'fcc'.")
            return

    lattice = input("  Lattice constant (Å) [3.40]: ").strip()
    if not lattice:
        lattice = "3.40"

    alloy_name = "-".join(elems)

    # ── Step 4: Simulation parameters ────────────────────────────────────────
    print("\nStep 4: Simulation parameters (press Enter to keep default).")
    params = parse_run_ed_params()
    if not params:
        print("  (using built-in defaults)")
        params = {"NCORE": "16", "NJOB": "4", "NCONFIG": "3",
                  "NDIR_PER_CONFIG": "100", "SIMTIME": "4.0",
                  "EMIN": "10", "EMAX": "150", "ESTEP": "2",
                  "TEMP": "40", "DEFECT_METHOD": "ovito"}

    editable = ["NCORE", "NJOB", "NCONFIG", "NDIR_PER_CONFIG",
                "SIMTIME", "EMIN", "EMAX", "ESTEP", "TEMP", "DEFECT_METHOD"]
    for key in editable:
        cur = params.get(key, "")
        hint = " [displace/cna/ptm/ovito]" if key == "DEFECT_METHOD" else ""
        new_val = input(f"  {key} [{cur}]{hint}: ").strip()
        if new_val:
            update_run_ed_param(key, new_val)
            params[key] = new_val

    # ── Step 5: Confirm ──────────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("  Summary")
    print("=" * 60)
    print(f"  Alloy:     {alloy_name}  ({elem_str})")
    print(f"  N elements: {n_elements}")
    print(f"  Potential: {pot_file}")
    print(f"  Config:    {config_source} ({params.get('NCONFIG','?')} configs)")
    if config_source == "auto":
        print(f"  Crystal:   {crystal_structure}")
    print(f"  Lattice:   {lattice} Å")
    print(f"  Cores:     {params.get('NCORE','?')} x {params.get('NJOB','?')} jobs")
    print(f"  Temp:      {params.get('TEMP','?')} K")
    print(f"  Defect:    {params.get('DEFECT_METHOD','?')}")

    confirm = input("\n  Proceed? [y/N]: ").strip().lower()
    if confirm != 'y':
        print("  Cancelled.")
        return

    # Generate alloy.conf and run
    generate_alloy_conf(alloy_name, n_elements, elem_str, masses_str,
                        lattice, pot_file, config_source, crystal_structure)

    print(f"\n  Alloy config written. Starting Ed calculation...")
    print(f"  Results will be saved to results/\n")

    try:
        subprocess.run(["bash", "run_Ed.sh"], cwd=ED_CALC_DIR)
    except KeyboardInterrupt:
        print("\n  TDE calculation interrupted.")
    except FileNotFoundError:
        print("ERROR: bash or run_Ed.sh not found. Check LAMMPS installation.")

    print("\n  TDE calculation finished.")


# ═══════════════════════════════════════════════════════════════════════════
#  Option 2: Plot Ed Convergence
# ═══════════════════════════════════════════════════════════════════════════

def find_results_dirs():
    """Scan Ed_calc/ for directories containing config_*/Ed_direction_*.txt."""
    results = []
    pattern = os.path.join(BASE_DIR, "**", "config_*", "Ed_direction_*.txt")
    for fpath in glob.glob(pattern, recursive=True):
        d = os.path.dirname(os.path.dirname(fpath))  # .../results-xxx/
        if d not in results:
            results.append(d)
    return sorted(results)


def run_ed_plot():
    print("\n--- Plot Ed Convergence (Ed_plot) ---\n")

    results_dirs = find_results_dirs()
    if not results_dirs:
        print("No results found. Run TDE calculation first (option 1).")
        return

    print("Available results directories:")
    for i, d in enumerate(results_dirs):
        rel = os.path.relpath(d, BASE_DIR)
        n_files = len(glob.glob(os.path.join(d, "config_*", "Ed_direction_*.txt")))
        print(f"  {i+1}. {rel}  ({n_files} directions)")

    choice = input(f"\n  Select [1-{len(results_dirs)}]: ").strip()
    try:
        idx = int(choice) - 1
        if idx < 0 or idx >= len(results_dirs):
            print("Invalid selection.")
            return
    except ValueError:
        print("Invalid input.")
        return

    target_dir = results_dirs[idx]

    # Copy plot_Ed.py and alloy.conf if not present
    plot_script = os.path.join(target_dir, "plot_Ed.py")
    template = os.path.join(ED_PLOT_DIR, "plot_Ed.py")
    if not os.path.exists(plot_script) and os.path.exists(template):
        shutil.copy(template, plot_script)
        print(f"  Copied plot_Ed.py -> {os.path.relpath(target_dir, BASE_DIR)}/")

    alloy_conf_src = os.path.join(ED_CALC_DIR, "alloy.conf")
    alloy_conf_dst = os.path.join(target_dir, "alloy.conf")
    if os.path.exists(alloy_conf_src) and not os.path.exists(alloy_conf_dst):
        shutil.copy(alloy_conf_src, alloy_conf_dst)
        print(f"  Copied alloy.conf -> {os.path.relpath(target_dir, BASE_DIR)}/")

    if not os.path.exists(plot_script):
        print("ERROR: plot_Ed.py not found and could not be copied.")
        return

    print(f"\n  Plotting in {os.path.relpath(target_dir, BASE_DIR)}/ ...\n")
    try:
        subprocess.run(["python3", "plot_Ed.py"], cwd=target_dir)
    except KeyboardInterrupt:
        print("\n  Plotting interrupted.")

    png_path = os.path.join(target_dir, "plot_Ed.png")
    if os.path.exists(png_path):
        print(f"\n  Saved: {os.path.relpath(png_path, BASE_DIR)}")


# ═══════════════════════════════════════════════════════════════════════════
#  Option 3: DPA Calculator
# ═══════════════════════════════════════════════════════════════════════════

def run_dpa_calc():
    print("\n--- DPA Calculator (NRT / ARC-DPA / CB-DPA) ---\n")
    script = os.path.join(DPA_CALC_DIR, "dpa_calculator.py")
    if not os.path.exists(script):
        print("ERROR: dpa_calculator.py not found.")
        return
    try:
        subprocess.run(["python3", script, "-i"])
    except KeyboardInterrupt:
        print("\n  DPA calculator interrupted.")


# ═══════════════════════════════════════════════════════════════════════════
#  Option 4: Clean Up
# ═══════════════════════════════════════════════════════════════════════════

def clean_up():
    print("\n--- Clean Up ---\n")

    targets = []

    # Ed_calc generated files
    for pattern in ["logs", "dump_files"]:
        for p in glob.glob(os.path.join(ED_CALC_DIR, pattern)):
            if os.path.isdir(p):
                targets.append(p)

    for pattern in ["results", "results-*"]:
        for p in glob.glob(os.path.join(BASE_DIR, pattern)):
            if os.path.isdir(p):
                targets.append(p)

    for pattern in ["data.equilibrated.*", ".equilibrated_model.*",
                     "directions.config_*.txt",
                     "rss_substitute.lmp"]:
        for p in glob.glob(os.path.join(ED_CALC_DIR, pattern)):
            if os.path.isfile(p):
                targets.append(p)

    for pattern in ["Ed_summary.txt"]:
        for p in glob.glob(os.path.join(BASE_DIR, pattern)):
            if os.path.isfile(p):
                targets.append(p)

    # Ed_plot generated files
    for pattern in ["plot_Ed.png"]:
        for p in glob.glob(os.path.join(ED_PLOT_DIR, pattern)):
            if os.path.isfile(p):
                targets.append(p)

    if not targets:
        print("No intermediate or result files found. Nothing to clean.")
        return

    print("The following files/directories will be deleted:")
    for t in sorted(targets):
        rel = os.path.relpath(t, BASE_DIR)
        if os.path.isdir(t):
            size = sum(os.path.getsize(os.path.join(dp, fn))
                       for dp, _, fns in os.walk(t) for fn in fns)
            print(f"  [dir]  {rel}  ({size / 1024:.0f} KB)")
        else:
            print(f"  [file] {rel}")

    total_items = len(targets)
    confirm = input(f"\n  Delete {total_items} item(s)? [y/N]: ").strip().lower()
    if confirm != 'y':
        print("  Clean up cancelled.")
        return

    deleted = 0
    for t in targets:
        try:
            if os.path.isdir(t):
                shutil.rmtree(t)
            else:
                os.remove(t)
            deleted += 1
        except Exception as e:
            print(f"  ERROR deleting {os.path.relpath(t, BASE_DIR)}: {e}")

    print(f"  Deleted {deleted}/{total_items} items.")
    print("  Source code, potential files, and data files are preserved.")


# ═══════════════════════════════════════════════════════════════════════════
#  Option 9: Environment Setup
# ═══════════════════════════════════════════════════════════════════════════

ENV_CONF_PATH = os.path.join(BASE_DIR, "env.conf")


def read_env_conf():
    """Read MPIRUN and LMP from env.conf. Returns dict with defaults."""
    defaults = {"MPIRUN": "mpirun", "LMP": "~/lmp-2023"}
    if not os.path.exists(ENV_CONF_PATH):
        return defaults
    with open(ENV_CONF_PATH) as f:
        for line in f:
            line = line.strip()
            if line.startswith("#") or not line:
                continue
            m = re.match(r'^(\w+)=(.*)$', line)
            if m and m.group(1) in defaults:
                defaults[m.group(1)] = m.group(2).strip().strip('"').strip("'")
    return defaults


def run_env_setup():
    print("\n--- Environment Setup ---\n")

    current = read_env_conf()
    print("Current settings:")
    print(f"  mpirun path: {current['MPIRUN']}")
    print(f"  LAMMPS path: {current['LMP']}")

    print("\nEnter new paths (press Enter to keep current):")
    new_mpirun = input(f"  mpirun path [{current['MPIRUN']}]: ").strip()
    new_lmp = input(f"  LAMMPS path [{current['LMP']}]: ").strip()

    mpirun_val = new_mpirun if new_mpirun else current["MPIRUN"]
    lmp_val = new_lmp if new_lmp else current["LMP"]

    with open(ENV_CONF_PATH, 'w') as f:
        f.write("# Environment configuration for TPE Calculator\n")
        f.write("# Set by main.py option 9. Sourced by Ed_calc/run_Ed.sh at startup.\n")
        f.write(f'MPIRUN="{mpirun_val}"\n')
        f.write(f'LMP="{lmp_val}"\n')

    print(f"\n  Saved to {os.path.relpath(ENV_CONF_PATH, BASE_DIR)}")
    print(f"  mpirun = {mpirun_val}")
    print(f"  LMP    = {lmp_val}")


# ═══════════════════════════════════════════════════════════════════════════
#  Main loop
# ═══════════════════════════════════════════════════════════════════════════

def main():
    while True:
        show_menu()
        try:
            choice = input("  Select [0-4, 9]: ").strip()
        except EOFError:
            print("\n  Goodbye.\n")
            sys.exit(0)

        if choice == "0":
            print("\n  Goodbye.\n")
            sys.exit(0)
        elif choice == "1":
            run_tde_calc()
        elif choice == "2":
            run_ed_plot()
        elif choice == "3":
            run_dpa_calc()
        elif choice == "4":
            clean_up()
        elif choice == "9":
            run_env_setup()
        else:
            print("\n  Invalid choice. Please select 0-4 or 9.")

        if choice in ("1", "2", "3", "4", "9"):
            try:
                input("\n  Press Enter to return to menu...")
            except EOFError:
                break


if __name__ == "__main__":
    main()
